services:
  streamlit_ml_apps:
    container_name: streamlit_ml_apps
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      - STREAMLIT_SERVER_RUNONSAVE=true
      - STREAMLIT_SERVER_FILEWATCHERTYPE="poll"
    ports:
      - 8501:8501
    volumes:
      - ./st_app:/app/st_app